config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :contenttypes
  resources :media
  root to: 'contacts#index'  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :media
	has_and_belongs_to_many :contenttypes
	
  	
end

app/models/contenttype.rb
class Contenttype < ActiveRecord::Base
has_and_belongs_to_many :contacts, dependent: :destroy
end

app/models/medium.rb
class Medium < ActiveRecord::Base
has_and_belongs_to_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
   def index
    @contacts = Contact.all
  end

  
  def show
    @contact = Contact.find(params[:id])
  end

  
  def new
    @contact = Contact.new
  end

  
  def edit
    @contact = Contact.find(params[:id])
  end

  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact, notice: 'Animal was successfully created.' 
    else
      render 'new' 
    end
  end

  
  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Animal was successfully updated.' 
    else
      render 'edit'
    end
  end

  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path, notice: 'Animal was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, medium_ids:[], contenttype_ids:[])
    end
end

app/controllers/contenttypes_controller.rb
class ContenttypesController < ApplicationController
    def index
      @contenttypes = Contenttype.all
    end	

  	def show
      @contenttype = Contenttype.find(params[:id])
  	end

  	def new
  		@contenttype= Contenttype.new
  	end

  	def edit
      @contenttype = Contenttype.find(params[:id])
  	end

    def create
      @contenttype = Contenttype.new(contenttype_params)
      if @contenttype.save
        redirect_to @contenttype, notice: 'Enclosure was successfully created.' 
      else
        render 'new' 
      end
    end

  	def update
    	@contenttype = Contenttype.find(params[:id])
      if @contenttype.update(contenttype_params)
        redirect_to @contenttype, notice: 'Enclosure was successfully updated.' 
      else
        render 'edit'
      end
    end

  	def destroy
      @contenttype = Contenttype.find(params[:id])
    	@contenttype.destroy
    	redirect_to contenttypes_path, notice: 'Enclosure was successfully destroyed.' 
    end

	private
    def contenttype_params
    	params.require(:contenttype).permit(:name)
		end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
    
    def index
    	@media = Medium.all
    end	

  	def show
      @medium = Medium.find(params[:id])
  	end

  	def new
  		@medium= Medium.new
  	end

  	def edit
      @medium = Medium.find(params[:id])
  	end

  	def create
  		@medium = Medium.new(medium_params)
  		if @medium.save
        redirect_to @medium, notice: 'Species was successfully created.' 
      else
        render 'new' 
      end
    end

  	def update
    	@medium= Medium.find(params[:id])
      if @medium.update(medium_params)
        redirect_to @medium, notice: 'Species was successfully updated.' 
      else
        render 'edit'
      end
    end
  	
    def destroy
    	@medium= Medium.find(params[:id])
      @medium.destroy
    	redirect_to media_path, notice: 'Species was successfully destroyed.' 
    end

	private
		def medium_params
    		params.require(:medium).permit(:name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contenttypes_helper.rb
module ContenttypesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.error_notification %>
  <div class= 'row'>
  	<%= f.input :name, label: false, placeholder:'Enter name of animal...' , input_html: {style: 'width:400px; margin-left:auto; margin-right:auto'} %>
  	<%= f.button :submit, 'Submit' %>
  </div>

  <div class='row'>
  	<div class = 'col-sm-6'> 
      <%= f.association :media, label: false, as: :check_boxes, collection: Medium.all.to_a, label_method: :name  %>
    </div>
    <div class = 'col-sm-6'>
      <%= f.association :contenttypes, label: false, as: :check_boxes, collection: Contenttype.all.to_a, label_method: :name  %>
  	</div>
  </div>

  
 
<% end %>

app/views/contacts/edit.html.erb
<div class= 'container text-center'>
	<h1>Edit Animal</h1>
	
	<%= render 'form' %><br>

	
	<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class= "container">
  <p id="notice"><%= notice %></p>
  <div class= 'text-center'>
    <%= link_to 'Create New Animal', new_contact_path%>
  </div> <br><br>
  <div class= "table-responsive">
    <table class= "table table-condensed table-hover table-bordered">
      <thead>
        <tr>
          <th>Animal</th>
          <th>Species</th>
          <th>Enclosure</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.name %></td>
            <td><%= contact.media.map(&:name).sort.join(", ") %></td>
            <td><%= contact.contenttypes.map(&:name).sort.join(", ") %></td>
            
            <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
            <td><%= link_to 'Delete', contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  
</div>

app/views/contacts/new.html.erb
<div class= 'container text-center'>
	<h3>Create an animal and select options for Species and Enclosures for which it should belong to:</h3><br>
	<%= render 'form' %><br>
	<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %><br>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contenttypes/_form.html.erb
<%= simple_form_for @contenttype do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: false, placeholder:'Enter name of enclosure...' , input_html: {maxlength: 100, style: 'width:400px; margin-left:auto; margin-right:auto'} %>
  <%= f.button :submit, 'Submit'%>
 
<% end %>

app/views/contenttypes/edit.html.erb
<div class= 'container text-center'>
	<h1>Edit Enclosure</h1>
	<%= render 'form' %><br>
	<%= link_to 'Back', contenttypes_path %>
</div>

app/views/contenttypes/index.html.erb
<p id="notice"><%= notice %></p>


<div class= 'text-center'>
    <%= link_to 'Create New Enclosure', new_contenttype_path%>
  </div>
<br>
<div class= "container">
  <div class= "table-responsive">
    <table class= "table table-condensed table-hover table-bordered">
      <thead>
        <tr>
          <th>Enclosure</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contenttypes.each do |contenttype| %>
          <tr>
            <td><%= contenttype.name %></td>
            <td><%= link_to 'Edit', edit_contenttype_path(contenttype) %></td>
            <td><%= link_to 'Delete', contenttype_path(contenttype), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
  
</div

app/views/contenttypes/new.html.erb
<div class= 'container text-center'>
	
	<h1>New Enclosure</h1>
	<%= render 'form' %><br>
	<%= link_to 'Back', contenttypes_path %>
</div>

app/views/contenttypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contenttype.name %>
</p>

<%= link_to 'Edit', edit_contenttype_path(@contenttype) %> |
<%= link_to 'Back', contenttypes_path %>

app/views/footer/_copyright.html.erb
<footer>
    <div class="container">
       	<div class="row">
            <div class="col-lg-12 text-center">
                
            </div>
        </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang= "en">
<head>
  <meta charset="utf-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zoo Challenge</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "navigation/navbar" %>
<%= yield %><br><br><br><br>
<%= render "footer/copyright" %>
</body>
</html>

app/views/media/_form.html.erb
<%= simple_form_for @medium do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: false, placeholder:'Enter name of species...' , input_html: {maxlength: 100, style: 'width:400px; margin-left:auto; margin-right:auto'} %>
  <%= f.button :submit, 'Submit' %>
<% end %>

app/views/media/edit.html.erb
<div class= 'container text-center'>
	
	<%= render 'form' %><br>
	<%= link_to 'Show', @medium %> |
	<%= link_to 'Back', media_path %>
</div>

app/views/media/index.html.erb
<p id="notice"><%= notice %></p>


<div class= 'text-center'>
    <%= link_to 'Create New Species', new_medium_path%>
</div><br>

<div class= "container">
  <div class= "table-responsive">
    <table class= "table table-condensed table-hover table-bordered">
      <thead>
        <tr>
          <th>Species</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @media.each do |medium| %>
          <tr>
            <td><%= medium.name %></td>
            <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
            <td><%= link_to 'Delete', medium_path(medium), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>
  
</div

app/views/media/new.html.erb
<div class= 'container text-center'>
	
	<h1>Create New Species</h1>
	<%= render 'form' %><br>
	<%= link_to 'Back', media_path %>
</div>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medium.name %>
</p>

<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/navigation/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <%= link_to 'Home', root_path, class: "navbar-brand"  %>
        </div>
        
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter Categories <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li role="separator" class="divider"></li>
                        <li><%= link_to 'Add Species', media_path%></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to 'Add Enclosure', contenttypes_path %></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>